project:
  type: website
  render:
    - "*.qmd"
    - "!datasets/"
  resources:
    - "assets/"
    - "datasets/"

website:
  title: "SDS 366"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: syllabus.qmd
        text: Syllabus
        
    right:
      - text: "Slides"
        menu:
          - text: "Class 2: Aesthetic mappings"
            href: slides/aesthetic-mappings.qmd
          - text: "Class 3a: Visualizing amounts"
            href: slides/visualizing-amounts.qmd
          - text: "Class 3b: Telling a story"
            href: slides/telling-a-story.qmd
          - text: "Class 4: Coordinate systems and axes"
            href: slides/coordinate-systems-axes.qmd
          - text: "Class 13: Figure design"
            href: slides/figure-design.qmd
        
      - text: "Worksheets"
        menu:
          - text: "Class 2: Aesthetic mappings"
            href: worksheets/aesthetic-mappings.qmd
          - text: "Class 3: Visualizing amounts"
            href: worksheets/visualizing-amounts.qmd
          - text: "Class 4: Coordinate systems and axes"
            href: worksheets/coordinate-systems-axes.qmd
        
    tools:
      - icon: github
        href: "https://github.com"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto


