project:
  type: website
  render:
    - "*.qmd"
    - "!datasets/"
    - "!assignments/"
    - "!apps/"
  resources:
    - "assets/"
    - "datasets/"
    - "assignments/"
    - "apps/bin/"

website:
  title: "SDS 366"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: syllabus.qmd
        text: Syllabus
        
    right:
      - text: "Slides"
        menu:
          - text: "Class 1: Introduction"
            href: slides/introduction.qmd
          - text: "Class 2: Aesthetic mappings"
            href: slides/aesthetic-mappings.qmd
          - text: "Class 3a: Visualizing amounts"
            href: slides/visualizing-amounts.qmd
          - text: "Class 3b: Telling a story"
            href: slides/telling-a-story.qmd
          - text: "Class 4: Coordinate systems and axes"
            href: slides/coordinate-systems-axes.qmd
          - text: "Class 5: Visualizing distributions 1"
            href: slides/visualizing-distributions-1.qmd
          - text: "Class 6: Visualizing distributions 2"
            href: slides/visualizing-distributions-2.qmd
          - text: "Class 7: Color scales"
            href: slides/color-scales.qmd
          - text: "Class 8: Color spaces and color-vision deficiency"
            href: slides/color-spaces.qmd
          - text: "Class 13: Figure design"
            href: slides/figure-design.qmd
        
      - text: "Worksheets"
        menu:
          - text: "Class 1a: Introduction to Quarto"
            href: worksheets/intro-to-Quarto.qmd
          - text: "Class 1b: Introduction to R"
            href: worksheets/intro-to-R.qmd
          - text: "Class 2: Aesthetic mappings"
            href: worksheets/aesthetic-mappings.qmd
          - text: "Class 3: Visualizing amounts"
            href: worksheets/visualizing-amounts.qmd
          - text: "Class 4: Coordinate systems and axes"
            href: worksheets/coordinate-systems-axes.qmd
          - text: "Class 5: Visualizing distributions 1"
            href: worksheets/visualizing-distributions-1.qmd
          - text: "Class 6: Visualizing distributions 2"
            href: worksheets/visualizing-distributions-2.qmd
          - text: "Class 7: Color scales"
            href: worksheets/color-scales.qmd
          - text: "Class 8: Color selection"
            href: worksheets/color-selection.qmd

      - text: "Resources"
        menu:
        - text: "Textbook"
          href: "https://clauswilke.com/dataviz"
          target: "_blank"
        - text: "Edupod"
          href: "https://edupod.cns.utexas.edu"
          target: "_blank"
        - text: "Color chooser app"
          href: apps/bin/choose-color/index.html
          target: "_blank"
        - text: "CVD simulations"
          href: apps/bin/cvd-emulator/index.html
        
    tools:
      - icon: github
        href: "https://github.com/wilkelab/SDS366"

format:
  html:
    theme:
      light: cosmo
      dark: [solar, theme-dark.scss]
    css: styles.css
    toc: true
  live-html:
    theme:
      light: cosmo
      dark: [solar, theme-dark.scss]
    css: styles.css
    toc: true
execute: 
  freeze: auto


