---
title: Disability and Access Accommodations
format: html
---

Some students receive special course accommodations from Disability and Access. Below is a list of common accommodation requests and my explanation of how I usually handle them. If you have any questions regarding any of these accommodations and/or have additional requests, please reach out to me on Canvas, in office hours, or after class and we can discuss.

## Classroom Accommodations

- **Use of technology to take notes during class.** You are welcome to use any note-taking technology you find helpful. To the extent that your note-taking technology creates any sort of recordings of class materials, see the next point.

- **Use of technology to audio record during class.** You are welcome to record audio, *for your own personal use as a study aid.* Audio recordings should not be shared or otherwise made available to third parties. Be aware that the section in the syllabus about [class recordings](syllabus.html#class-recordings) applies to any personal recordings you may be making.

- **A copy of class notes from a volunteer.** I am happy to ask whether there are any volunteers willing to share class notes.

- **Access to materials shown in class.** All materials are posted either on Canvas or on the class website, <https://wilkelab.org/SDS366>.

- **Flexibility with deadlines.** The amount of flexibility we can provide is strongly constrained by the class structure. We cannot accept homework submissions after the assignment has been graded and solutions have been released. This will typically happen 2-3 days after the original deadline. We cannot accept project submissions after the project has been released for peer grading. This will happen 2 days after the original deadline. In all cases, if you need a deadline extension please reach out on Canvas as early as possible (ideally before the deadline has passed) and ask for a specific amount of time you would like to have added to the deadline. (Example: "Could I have a deadline extension of one day?") Mention in your message that you have an approved accommodation for flexibility with deadlines. You do not need to explain _why_ you need the extension. 

  Please note that deadline extensions should be occasional, one-off events. I will not approve a blanket deadline extension for all assingments throughout the semester. I also encourage you to manage your deadlines proactively. Materials for homework assignments will be posted at least one week before the deadline, and materials for projects will be posted at least two weeks before the deadline. This should give you plenty of time to complete your assignments early and not push things to the last minute.

- **Flexibility with attendance.** Regular attendance is a component of the overall grade in this class. However, you are not required to attend every single lecture. You only need to attend 20 of the lectures for full points.


## Testing accommodations

This class does not have any timed exams or tests and therefore testing accommodations do not apply.