---
title: Syllabus
format: html
---


## Course title and instructor

**Title:** SDS 366 Data Visualization in R<br>
**Semester:** Spring 2026<br>
**Unique:** 60450, TTH 3:30pm-5:00pm, UTC 3.134<br>

**Instructor:** Claus	O.	Wilke<br>
**Email:** wilke@austin.utexas.edu<br>
**Office Hours:** Mon. 9am–10am (open Zoom), Wed. 10am–11am (open Zoom), or by appointment<br>

**Teaching Assistant:** Luiz Vieira<br>
**Email:** luiz.vieira@austin.utexas.edu<br>
**Office Hours:** Wed. 1pm–2pm (open Zoom), Thurs. 1pm–2pm (open Zoom), or by appointment<br>


## Purpose and contents of the class

In this class, students will learn how to visualize data sets and how to reason about and communicate with data visualizations. A substantial component of this class will be dedicated to learning how to program in R. In addition, students will learn how to compile analyses and visualizations into reports, how to make the reports reproducible, and how to post reports on a website or blog.

## Prerequisites

The class requires no prior knowledge of programming. However, students are expected to have successfully completed an introductory statistics class taught with R, such as SDS 320E, and they are expected to have some basic familiarity with the statistical language R.


## Textbook

This class draws heavily from materials presented in the following book:

- Claus O. Wilke. [Fundamentals of Data Visualization.](https://clauswilke.com/dataviz) O'Reilly Media, 2019.

Additionally, we will also make use of the following books:

- Hadley Wickham, Danielle Navarro, and Thomas Lin Pedersen. [ggplot2: Elegant Graphics for Data Analysis, 3rd ed.](https://ggplot2-book.org/) Springer, to appear.

- Kieran Healy. [Data Visualization: A Practical Introduction.](https://socviz.co/) Princeton University Press, 2018.

All these books are freely available online and you do not need to purchase a physical copy of either book to succeed in this class.


## Topics covered

------------------------------------------------------------------
  Class Topic                       Coding concepts covered
------- --------------------------- ------------------------------
1.      Introduction, reproducible  RStudio setup online, Quarto
        workflows

2.      Aesthetic mappings          **ggplot2** quickstart

3.      Visualizing amounts,        `geom_col()`, `geom_point()`,
        telling a story             position adjustments

4.      Coordinate systems and      coords and position scales
        axes

5.      Visualizing distributions   stats, `geom_density()`,
        1                           `geom_histogram()`

6.      Visualizing distributions   violin plots, sina plots, ridgeline plots
        2

7.      Color scales                color and fill scales

8.      Color spaces, color vision  **colorspace** package
        deficiency

9.      Data wrangling              `mutate()`, `filter()`, `arrange()`
                                    `summarize()`, `join()`, `pivot_longer()`

10.     Visualizing proportions     bar charts, pie charts

11.     Getting to know your data   handling missing data, `is.na()`, `case_when()`

12.     Getting things into the     `fct_reorder()`, `fct_lump()`
        right order

13.     Figure design               ggplot themes

14.     Compound figures            **patchwork** package

15.     Visualizing trends          `geom_smooth()`

16.     Functions and functional    `map()`, `nest()`, **purrr** package
        programming

17.     Working with models         `lm`, `cor.test`, **broom** package

18.     Visualizing uncertainty     frequency framing, error bars, **ggdist** package

19.     Dimension reduction 1       PCA

20.     Dimension reduction 2       kernel PCA, t-SNE, UMAP

21.     Clustering 1                k-means clustering

22.     Clustering 2                hierarchical clustering
        
23.     Redundant coding, text      **ggrepel** package
        annotations

24.     Dealing with overplotting   jittering, 2d histograms,
                                    contour plots

25.     Visualizing geospatial      `geom_sf()`, `coord_sf()`
        data

26.     Interactive plots           **ggiraph** package

27.     Web technologies and        CSS
        web design

28.     Animations                  **gganimate** package


----------------------------------------------------------------


## Computing requirements

Programming needs to be learned by doing, and a significant portion of the in-class time will be dedicated to working through simple problems. All programming exercises will be available through a web-based system, so the only system requirement for student computers is a modern web browser.

## Course site

All materials and assignments will be posted on the course webpage at:
[https://wilkelab.org/SDS366](https://wilkelab.org/SDS366)

Assignment deadlines are shown on [the schedule.](https://wilkelab.org/SDS366/schedule.html)

Assignments will be submitted and grades will be posted [on Canvas.](https://utexas.instructure.com)

Participation via presence in class and in online discussions will also be tracked on Canvas.

R compute sessions are available at:
[https://edupod.cns.utexas.edu](https://edupod.cns.utexas.edu)  
Note that edupods will be unavailable due to maintenance approximately two hours per month, usually on a Thursday afternoon between 4pm and 6pm. Specific maintenance times are published in advance on the [RCTF wiki.](https://wikis.utexas.edu/display/RCTFusers)

## Assignments and grading

The graded components of this class will be homeworks, projects, peer-grading, and participation. Each week either a homework, a project, or a peer-grading is due. Homeworks will be relatively short visualization problems to be solved by the student, usually involving some small amount of programming to achieve a specified goal. They are graded by the TA. Projects are larger and more involved data analysis problems that involve both programming and writing. They are peer-graded by the students. Students will have at least one week to complete each homework and two weeks to complete each project. The submission deadlines for homeworks and projects will be Thursdays at 11pm.

There will be seven homeworks and three projects. Both homeworks and projects need to be submitted electronically on Canvas. Homeworks are worth 8 points and projects are worth 100 points.

Projects are peer-graded, which involves evaluating four projects by other students according to a detailed grading rubric that will be provided. The final grade for each project is the mean of the highest three peer grades (the lowest one is dropped), subject to oversight and potential grade correction (up or down, as warranted) by the TA. The peer-grading itself will also be graded by the TA. Experience has shown that peer-grading is often the most instructive component of this class, so don't take this lightly.

Participation is assessed via lecture attendance. Students will receive 1 point for every lecture they attend, up to a maximum of 20 points. (This means students can miss up to six lectures throughout the semester without receiving any grade penalty.) Attendance is tracked via simple quizzes on Canvas. No participation is assessed in the first week of class.

Assignment type   Number     Points per assignment  Total points
--------------- ---------- ----------------------- -------------
Homework          7                              8            56
Project           3                            100           300
Peer grading      3                              8            24
Participation     20                             1            20


Thus, in summary, each project contributes 25% to the final grade, and the totality of all homeworks, attendance, and peer grading contributes another 25% to the final grade. **There are no traditional exams in this class and there is no final.**

The	class	will use +/- grading, and the exact grade boundaries will be determined at the end of the semester. However, the following minimum grades will be guaranteed:	

 Points achieved  Minimum guaranteed grade
---------------- -------------------------
       360 (90%)                        A-
       320 (80%)                        B-
       280 (70%)                        C-
       200 (50%)                        D-

## Late assignment policy

Homeworks that are submitted past the posted deadline will not be graded and will receive 0 points.

Project submissions will have a 1-day grace period. Projects submitted during the grace period will have 25 points deducted from the obtained grade. After the grace period, students who have not submitted their project will receive 0 points.

Peer grades need to be submitted by the posted deadline. Late submissions will result in 0 points for the peer-grading effort.

In case of illness or other unforeseen circumstances out of your control, please reach out to Claus Wilke as soon as possible. We will consider your request on a case-by-case basis. If you need a deadline extension for valid reasons, please reach out *before* the official submission deadline and state how much of an extension you would need. Whether deadline extensions are possible depends on the severity of your situation as well as whether the solutions to the assignment have already been published.

## Office hours

Both the graduate TA and myself will be available at posted times or by appointment. Office hours will be over Zoom. The most effective way to request an appointment for office hours outside of posted times is to suggest several times that work for you.  I would suggest to write an email such as the following:

    Dear Dr. Wilke,
    
    I would like to request a meeting with you outside of 
    regular office hours this week. I am available Thurs.
    between 1pm and 2:30pm or Fri. before 11am or after 4pm.
    
    Thanks a lot,
      John Doe

Note that we will not usually make appointments before 9am or after 5pm.

## Email policy

When emailing about this course, please put "SDS366" into the subject line. Emails to the instructor or TA should be restricted to organizational issues, such as requests for appointments, questions about course organization, etc. For all other issues, post in the discussions on Canvas, ask a question during open Zoom, or make an appointment for a one-on-one session.

Specifically, we will not discuss technical issues related to assignments over email. Technical issues are questions concerning how to approach a particular problem, whether a particular solution is correct, or how to use the statistical software R. These questions should be posted on the Discussion forums on Canvas. Also, we will not discuss grading-related matters over email. If you have a concern about grading, schedule a one-on-one Zoom meeting.

## Special accommodations

**Students with disabilities.** If you are a student with a disability, or think you may have a disability, and need accommodations please contact Disability and Access (D&A). You may refer to D&A’s website for contact and more information: [https://disability.utexas.edu/.](https://disability.utexas.edu/) If you are already registered with D&A, please deliver your Accommodation Letter to me as early as possible in the semester so we can discuss your approved accommodations.

**Religious holy days.** Students who must miss a class or an assignment to observe a religious holy day will be given an opportunity to complete the missed work within a reasonable time after the absence. According to UT Austin policy, such students must notify me of the pending absence at least fourteen days prior to the date of observance of a religious holy day. 

## Academic dishonesty

This course is built upon the idea that student interaction is important and a powerful way to learn. We encourage you to communicate with other students, in particular through the discussion forums on Canvas. However, there are times when you need to demonstrate your own ability to work and solve problems. In particular, your homeworks and projects are independent work, unless explicitly stated otherwise. You are allowed to confer with fellow students about general approaches to solve the problems in the assignments, but you have to do the assignments on your own and describe your work in your own words. Students who violate these expectations can expect to receive a failing grade on the assignment and will be reported to Student Judicial Services. These types of violations are reported to professional schools, should you ever decide to apply one day. Don’t do it—it’s not worth the consequences.

## Use of generative AI tools

Generative AI tools such as ChatGPT or Copilot are becoming increasingly popular and widely used. In this class, you are allowed to use such tools as an aid for completing your assignments. **However, you are ultimately responsible for the work you deliver.** If the Generative AI makes mistakes, such as using R packages that are not permitted, violating design principles that have been discussed in class, or generally producing sub-standard assignments, that is on you. Your assignments will be graded accordingly.

We would also like to offer some words of caution. Given the depth and specific attention that this course places on effective visualization, current AI tools will frequently produce bad results that are not up to the standards expected in this class. In addition, the code produced will often not follow the approaches shown in slides or worksheets and will be difficult for your peers to grade. These deficits will become apparent especially as we transition into more complex assignments and projects.

More generally, you will only get out of this class as much as you invest into it, and overly relying on AI tools will prevent you from building skills needed later in the class and will cause you to struggle as the complexity and depth of the course content increases.

## Sharing of course materials is prohibited

Any materials in this class that are not posted publicly may not be shared online or with anyone outside of the class unless you have my explicit, written permission. This includes but is not limited to lecture hand-outs, videos, assessments (quizzes, exams, papers, projects, homework assignments), in-class materials, review sheets, and additional problem sets. Unauthorized sharing of materials promotes cheating. It is a violation of the University’s Student Honor Code and an act of academic dishonesty. We are well aware of the sites used for sharing materials, and any materials found online that are associated with you, or any suspected unauthorized sharing of materials, will be reported to Student Conduct and Academic Integrity in the Office of the Dean of Students. These reports can result in sanctions, including failure in the course.

Any materials posted on the public class website ([https://wilkelab.org/SDS366/](https://wilkelab.org/SDS366/)) are considered public and can be shared under the Creative Commons Attribution [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) license.

## Class recordings

In case any class recordings are provided they are reserved only for students in this class for educational purposes and are protected under FERPA. The recordings should not be shared outside the class in any form. Violation of this restriction by a student could lead to Student Misconduct proceedings.
